### ISSUE TITLE
IgxPivotGrid + IgxPivotDataSelector [Feature progress]

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#10309]
## Specifications

Data Operations spec: [Pivot Pipes Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Pivot-Pipes-Specification)
IgxPivotGrid spec: [Pivot Grid Specification](https://github.com/IgniteUI/igniteui-angular/wiki/igxPivotGrid-Specification)
IgxPivotDataSelector spec: TBA

## Branch

Feature branch: https://github.com/IgniteUI/igniteui-angular/tree/pivot-grid-master

### Data Operations

- [x] Specification
   - [x] Test Plan
- [x] Dimensions
   - [x] Row Dimensions
   - [x] Column Dimensions
   - [x] Predefined dimensions
- [x] Measures
   - [x] Predefined measures
- [x] Binding to data with complex objects

### Pivot Grid Component

- [x] Specification
    - [x] Test Plan
- [x] *Filtering (depends on Spec)*
    - [x]  Integrate flat excel style filtering
    - [x]  Integrate excel style filtering in a tree view (P2) - TBD separately
- [x] *Column Dimensions UI (depends on Spec)*
- [x] *Row Dimensions UI (depends on Spec)*
- [x] IPivotDimensions update options
- [x] Expand collapse states
- [x] Formatting and measure styling
- [x] Base Grid API Hiding
- [x] Sorting
     - [x] Sorting dimension values via chip.
     - [x] Sorting data values via headers.
- [x] Value aggregation selection via chip.
- [x] Dimension selection
- [x] Dimensions Cell Merging (P2)
  - [x] Row dimensions merging - https://github.com/IgniteUI/igniteui-angular/issues/10800
  - [x] Column dimensions merging - https://github.com/IgniteUI/igniteui-angular/issues/10801
- [x] Keyboard navigation in headers
- [x] Styling - @desig9stein 
- [x] Ultra-compact pivot density (P2)
- [x] Dev Samples
   - [x] Complex data dev sample
   - [x] Remote data sample
- [x] Create Sample - igniteui-angular-samples
- [x] Improve scrolling performance
   - [x] Clear old columns from view - https://github.com/IgniteUI/igniteui-angular/pull/10502
   - [x] Ensure that when columns are created for row dimensions while scrolling the grid does not repaint. - https://github.com/IgniteUI/igniteui-angular/pull/10739 
- [x] Allow resizing/auto-sizing the row dimension columns in case their text overflows - https://github.com/IgniteUI/igniteui-angular/issues/10811
- [x] Allow resizing row dimensions - https://github.com/IgniteUI/igniteui-angular/issues/10717
- [x] Implement filtering chips dropdown in PivotGrid UI - https://github.com/IgniteUI/igniteui-angular/issues/10713
- [x] Implement drop area for the chips UI in the pivot dimensions - https://github.com/IgniteUI/igniteui-angular/issues/10712

### Pivot Data Selector Component

- [x] Specification - @StefanIvanov

### Documentation
- [x] Write a topic for PivotGrid

### Samples
- [x] Create a sample

**Comment by kdinev** [comment]
Related #5700

**Comment by dkamburov** [comment]
@kdinev #3514 shouldn't be part of the PivotGrid efforts, yesterday there was a discussion about it and it will be difficult to implement the same merging functionality for the values of the grid and for the headers of the Pivot:
![image](https://user-images.githubusercontent.com/1182001/148545769-655e67ae-4d9c-46ea-a1b6-e45b64b60dfe.png)
In PivotGrid there are cases when two adjacent equal values shouldn't merge(screenshot), while into the grid - all equal adjacent cells should be merged(this one is also bound with the sorting). So the pivot headers merging should not to be part of the base grid merging of the cells.

**Comment by kdinev** [comment]
I'm adding it only as related. I'm not suggesting to make it part of the pivot grid effort!
