### ISSUE TITLE
Improve package tree-shaking

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#13562]
## Is your feature request related to a problem? Please describe.
Currently there's parts of the packages that are not tree-shaken optimally, like:

- [x] i18n resouces (`igniteui-angular-i18n`) #13411
- [x] `trial-watermark` #13442 
- [x] i18n built-in EN resources #13493 
- [x] animations #13494 
- [x] text highlight directive #13915 
- [x] utils 
- [x] #13677
- [x] grid #13412
- [x] grid paginator #13896
- [x] grid toolbar #13897
- [x] grid action strip #13900

## Describe the solution you'd like
The code for the parts mentioned above should be tree-shaken when not used.

**Comment by kdinev** [comment]
@damyanpetev @igdmdimitrov About the text-highlight directive/service. Who should be the right person to own the refactoring?

**Comment by kdinev** [comment]
@damyanpetev @igdmdimitrov I'm reopening the issue because of the text-highlight. I still need an answer on who the owner of this should be (an issue needs to be created). Utils can also benefit from further refactor.

**Comment by damyanpetev** [comment]
@kdinev Well I have to look at the small utils things that weren't tree shaking after the updates anyway, so I might as well have a look at the highlight directive too

**Comment by kdinev** [comment]
@damyanpetev I suggest separate issues be logged for each!

**Comment by kdinev** [comment]
@damyanpetev Could you update the checklist with the ideas you had about refactoring the grid paginator usage for better tree-shaking?
