### ISSUE TITLE
Refactor width/height calculation logic i.e. `calculateGridSizes` function

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#4816]
## Description 
Right now we get a lot of bugs related to different resizing scenarios caused by this function.

## Related Bugs
#3950
#3949
#4745
#1861 
#1858 
#4839
https://github.com/IgniteUI/igniteui-angular/issues/5573

## TODO 
- [ ] Remove multiple `resetCaches` calls
- [ ] Remove multiple `detectChanges` calls
- [ ] Optimize multiple calls to `calculateGridSizes` during initialization
- [ ] [Optional] See if we can remove the grid TBODY pixel sizing

 * igniteui-angular version: 7.2.x
 * browser: *

**Comment by tachojelev** [comment]
Possibly related to #4855
