### ISSUE TITLE
Drag and Drop improvements

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular#5319]
Drag and drop improvements:

- [x] [Dragging without ghost](https://github.com/IgniteUI/igniteui-angular/wiki/Drag&Drop-Directives-Specification#dragging-without-ghost)
- [x] [Ghost template](https://github.com/IgniteUI/igniteui-angular/wiki/Drag&Drop-Directives-Specification#dragging-with-ghost-element)
- [x] [Dragging using a handle](https://github.com/IgniteUI/igniteui-angular/wiki/Drag&Drop-Directives-Specification#dragging-using-a-handle)
- [x] [Linking of drag and drop elements](https://github.com/IgniteUI/igniteui-angular/wiki/Drag&Drop-Directives-Specification#linking-drag-to-drop-element)
- [x] [Drop strategies](https://github.com/IgniteUI/igniteui-angular/wiki/Drag&Drop-Directives-Specification#drop-strategies)
- [x] [Drag animations](https://github.com/IgniteUI/igniteui-angular/wiki/Drag&Drop-Directives-Specification#animations)
- [x] [Update API / Add migration on changed API](https://github.com/IgniteUI/igniteui-angular/wiki/Drag&Drop-Directives-Specification#api)
- [x] Update components/features based on igxDrag/igxDrop - Chips/ColumnMoving/RowDrag - Will be addressed in issue https://github.com/IgniteUI/igniteui-angular/issues/5685

**Comment by radomirchev** [comment]
#1266 Drag and Drop new samples - still "Open"
Checklist not completed.

**Comment by mpavlinov** [comment]
@radomirchev Checklist is completed. The last point we will address in another issue.
