### ISSUE TITLE
Calendar KB navigation issues

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#5856]
## Description  
  igniteui-angular version: 8.2.x

- [x] Navigating with tab key should NOT focus outside month dates that are hidden.

- [x] Should not be able to navigate with Tab key to a disabled date.

- [x] When open month view or year view and press "Page Down" or "Page Up" should NOT be thrown error.

- [x]  When the first date from the first moth in the view is disabled can not navigate with ArrowLeft or ArrowUp.

- [x]  When the subheader is templated, an error is thrown in the console after clicking on the month/year caption and then choose a new month/year

 ![image](https://user-images.githubusercontent.com/34240583/65601757-56318b80-dfab-11e9-86fc-b38039def1ad.png)

- [x] Focus is not moved properly when navigating in the calendar. The  focus is always moved to the selected data - will be fixed with #5888 

- [x] In IE11 when click on a date and press arrow key, no date is activated. The focus should be moved accordingly the pressed arrow key.  #5895

- [x] In IE11 when click on the next arrow and then press enter the calendar is broken and the page crashes. - Not reproducible after latest update for WIndows 10

![image](https://user-images.githubusercontent.com/34240583/65602380-76157f00-dfac-11e9-99d0-e84d3f5178de.png)

- [x] Not correct year/ month is selected when click over second or further month view

##### Steps to reproduce  
1. Open the calendar dev sample 
2. Make sure that the first month that is displayed is December 2019
3. Click over the year or month in the second month view

#### Result  
Selected year is 2019, or selected month is December

#### Expected result  
Selected year should be 2020, or selected month should be January
![image](https://user-images.githubusercontent.com/34240583/65600778-79f3d200-dfa9-11e9-93dd-91299c8c65c1.png)

- [x] When in first month all dates are disabled an press home key, no date is selected. In this case first active date should be selected
- [x] When navigating with page Up or page Down and the active date is not in the first view, the active date is not preserved - will be fixed with #5888 

Styling:
- [x] Arrows are misaligned with month title in IE11
