### ISSUE TITLE
Fix tests failing with Ivy / NG9

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#6175]
Related to #6146

- IgxChip

   - [ ] should render prefix element inside the chip before the content
   - [ ] should fire onSelection event when selectable is true

- IgxChipArea
   - [ ] should be able to select chip using api when selectable is set to false
   - [ ] should reorder chips when shift + leftarrow and shift + rightarrow is pressed

- IgxGrid Multi Row Layout - Keyboard navigation
   - [ ] should scroll focused cell fully in view when navigating with arrow keys and row is partially visible.

- IgxGrid - multi-row-layout Integration - Pinning 
   - [ ] should work with horizontal virtualization on the unpinned groups.

- IgxGrid Component Tests | IgxGrid - default rendering for rows and columns
   - [ ] should render all records exactly if height is 100% and parent container's height is unset and
   - [ ] should keep auto-sizing if initial data is empty then set to a new array
   - [ ] should keep auto-sizing if initial data is set to empty array that is then filled
   - [ ] should not render with calcHeight null at any point when loading data and
   - [ ] should keep auto-sizing if initial data is set to small array that is then filled
   - [ ] should render with calcHeight null if initial data is small but then
   - [ ] should keep default height when filtering
   - [ ] should not keep default height when lower the amount of bound data
   - [ ] should not keep auto-sizing when changing height

- IgxGrid - GroupBy
   - [ ] should reorder groups when reordering chip
   - [ ] should remove expansion state when reordering chips

**Comment by damyanpetev** [comment]
I looked into the first two for the Chip:
- should render prefix element inside the chip before the content
	`igx-chip__select--hidden` on the selected icon container applies a width transition on the icon
	so it's still animating on this check happens, so width is not 0
- should fire onSelection event when selectable is true
	Same issue with the initial transition, except this time the selection happens instantly, the chip being selected doesn't animate, in turn doesn't trigger the event that uses onSelectTransitionDone. 
	But hey, *all* other chips instead emit selection event from that initial animation :)

Seems like that's not intended and I'll submit an issue for it in a bit.

**Comment by radomirchev** [comment]
All issues linked to the EPIC are resolved.
