### ISSUE TITLE
Improve input components experience - date picker, time picker, calendar, etc.

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#6345]
## igxRangeDatePicker roadmap

 - [x] [igxMask refactoring](6454) ([PR](https://github.com/IgniteUI/igniteui-angular/pull/6455))
 - [x] [igxDateTimeEditorDirective new](6271) - this includes changes in the igxInput, igxInputGroup (so that it recognize new directive), igxDatePicker and igxTimePicker (functionalities are extracted from both and impimented in the igxDateEditor). [specification](https://github.com/IgniteUI/igniteui-angular/wiki/DateTime-Editor-Specification)
---
 - [ ] [igxCalendar keyboard navigation accessibility](6275)
 - [ ] [igxCalendar ARIA](6272)
---
 - [x] [igxRangeDatePicker](5732)

## Refactoring after the new igxDateTimeEditorDirective 
 - [ ] [igxDatePicker refactoring](6483)
 - [ ] [igxDateTime refactoring](6482)

## Bugs and Features
 - [ ] [Bind Input [Group] validity directly to ngModel so it responds better to changes through API](6434)
 - [x] [Input Group consistent focus](6531)
 - [ ] [IgxInput directive to style file type input](6544)
 - [x] [igxDatePicker and igxTimePicker doesn't handle required properly](6471) - this is added in the igDateTimeEditorDirective [specification](https://github.com/IgniteUI/igniteui-angular/wiki/DateTime-Editor-Specification), however it can be fixed before the refactoring of the igxDatePicker and igxTimePicker.
  - [ ] [igxDatePicker ARIA](6346)
  - [x] [igxTimePicker Define different styling for hours/minutes outside min and max values](3978) - design team has added the new stlyes, but implementation can wait until igxDateTime is refactored.
  - [ ] [scroll speed for igxTimePicker on mobile devices to high](6292)
  - [ ] [Full-width characters can be entered when mode is set to ”editable” or “dropdown](6427)
 - [ ] [Calling triggerTodaySelection in igxDatePicker throws error](5525)

**Comment by Lipata** [comment]
Closing this in favor of the following boards, which contains the Roadmap for those (and other) improvements:

 - [Inputs and DateTime Inputs](https://github.com/orgs/IgniteUI/projects/135)
 - [PwnJS](https://github.com/orgs/IgniteUI/projects/203)
