### ISSUE TITLE
Tests Refactoring

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#6438]
## Description  
Tests Refactoring

We need to refactor all the angular test.
All the, which are integration test with more than 5 user interaction should be refactor or excluded.
Here is a dodument for writing test:
https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular

Tests specs list:
### Non grid components:

- [ ] Avatar

- [ ] Badge

- [ ] igxBanner

- [x] IgxButtonGroup and IgxButton - @igdmdimitrov (Deferred)

- [x] IgxCalendar - @igdmdimitrov 

- [ ] Multi-View Calendar

- [ ] Card

- [ ] IgxMonthPicker

- [ ] Carousel

- [ ] IgxCheckbox

- [x] IgxChip - @nrobakova 

- [x] IgxChipsArea - @skrustev 

- [x] igxCombo - @PlamenaMiteva 

- [ ] Utils

- [ ] DataUtil

- [ ] IgxDatePicker

- [ ] Dialog

- [ ] IgxAutocomplete

- [ ] Divider

- [ ] igxFocus

- [ ] igxDrag/igxDrop

- [x] IgxForOf directive - @skrustev 

- [ ] IgxInput and IgxInputGroup

- [ ] IgxLayoutDirective

- [ ] igxMask

- [ ] IgxRadioGroupDirective

- [x] Scroll Inertia Directive - @skrustev 

- [ ] IgxHighlight and IgxSelection

- [ ] IgxToggle

- [ ] IgxTooltip

- [x] IgxDropDown - @PlamenaMiteva 

- [ ] igxExpansionPanel

- [ ] Icon Service

- [ ] List

- [ ] IgxNavbar

- [ ] IgxPaginator 

- [ ] IgCircularBar

- [ ] IgLinearBar

- [ ] IgxRadio

- [ ] igxSelect

- [ ] CSV Grid Exporter, CSV exporter and Excel Exporter - @igdmdimitrov 

- [ ] igxOverlay

- [ ] IgxTransaction

- [ ] IgxSlider

- [ ] IgxSnackbar

- [ ] IgxSwitch

- [ ] IgxBottomNav

- [ ] IgxTabs

- [ ] IgxTimePicker

- [ ] IgxToast

### Grid tests:

- [x] IgxGrid - Cell component - @nrobakova 

- [ ] IgxGrid - multi-column headers

- [x] Column Hiding UI - @nrobakova

- [ ] IgxGrid - Column Moving

- [x] Column Pinning UI - @nrobakova 

- [x] IgxGrid - Deferred Column Resizing

- [ ] IgxGrid - Column properties - TBC @nrobakova 

- [ ] IgxGrid - Cell Editing

- [ ] IgxGrid - Cell selection

- [x] IgxGrid - Clipboard

- [x] IgxGrid - Filtering actions UI - @nrobakova 

- [x] IgxGrid - Filtering Row UI actions - @nrobakova 

- [x] IgxGrid - Advanced Filtering - @igdmdimitrov

- [x] IgxGrid - Filtering actions - Excel style filtering - @nrobakova 

- [ ] IgxGrid - Filtering actions

- [x] IgxGrid - Keyboard navigation - @nrobakova 

- [ ] IgxGrid Multi Row Layout

- [ ] IgxGrid Component

- [x] IgxGrid - Row Editing - @valadzhov

- [x] IgxGrid - Row Selection - @nrobakova 

- [x] IgxGrid - Summaries - @nrobakova 

- [x] IgxGrid - Grid Toolbar - @igdmdimitrov 

- [ ] IgxGrid - CRUD operations - @valadzhov

- [ ] IgxGrid - GroupBy - @ChronosSF

- [ ] IgxGrid - Master Detail

- [x] IgxGrid - multi-row-layout keyboard navigation - @skrustev 

- [ ] IgxGrid - multi-row-layout Integration

- [ ] IgxGrid - multi-row-layout - TBD

- [x] IgxGrid - Grid Paging - @HristoP96

- [x]  IgxGrid - Column Pinning - @HristoP96

- [x] IgxGrid - search API - @igdmdimitrov 

- [x] IgxGrid - Grid Sorting - @HristoP96 

- [x] IgxGrid - Row Drag Tests - @PlamenaMiteva 

- [ ] IgxGridState

### Tree Grid:

- [ ] IgxTreeGrid - CRUD

- [ ] IgxTreeGrid - Expanding / Collapsing

- [ ] IgxTreeGrid - Filtering actions

- [ ] IgxTreeGrid - Indentation

- [ ] IgxTreeGrid - Integration

- [x] IgxTreeGrid - Key Board Navigation

- [ ]  IgxTreeGrid - Multi Cell selection

- [ ] IgxTreeGrid - search API

- [ ] IgxTreeGrid - Selection

- [ ] IgxTreeGrid - Sorting

- [ ] IgxTreeGrid - Summaries

- [ ] IgxTreeGrid Component Tests

### Hierarchical Grid:

- [x] IgxHierarchicalGrid Integration - @ChronosSF

- [x] IgxHierarchicalGrid Basic Navigation - @skrustev 

- [x] IgxHierarchicalGrid Complex Navigation - @ChronosSF

- [x] IgxHierarchicalGrid Multi-layout Navigation - @ChronosSF 

- [x]  IgxHierarchicalGrid Smaller Child Navigation - @ChronosSF

- [x] IgxHierarchicalGrid selection - @HristoP96

- [ ] Basic IgxHierarchicalGrid

- [ ] IgxHierarchicalGrid Row Islands

- [ ] IgxHierarchicalGrid Children Sizing

- [ ] IgxHierarchicalGrid Remote Scenarios

- [ ] IgxHierarchicalGrid Template Changing Scenarios

- [ ] IgxHierarchicalGrid Runtime Row Island change Scenarios

- [ ] IgxHierarchicalGrid custom template

- [ ] IgxHierarchicalGrid Virtualization

- [ ] IgxHierarchicalGrid Virtualization Custom Scenarios
