### ISSUE TITLE
Splitter

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular#6639]
## Describe the solution you'd like
I would like to have a Splitter layout UI that provides resizable, expandable, collapsible, nestable panes and control of the page layout

Spec: https://github.com/IgniteUI/igniteui-angular/wiki/Splitter-Specification

- [x] Basic implementation - based on igxDrag directive -> https://github.com/IgniteUI/igniteui-angular/pull/6985
- [x] Expand/Collapse panes. -> #7036
- [x] Keyboard interactions -> #7052 
- [x] RTL support
- [x] Automation
- [x] Styling - https://github.com/igniteui/igniteui-angular/issues/6949
- [x] Documentation - https://github.com/igniteui/igniteui-docfx/issues/1842
- [x] Samples - https://github.com/igniteui/igniteui-angular-samples/issues/1880
