### ISSUE TITLE
Row Pinning IgxGrid

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular#6640]
## Describe the solution you'd like
I would like to be able to pin/freeze rows on top/bottom of IgxGrid.

Sub-Tasks:

- [x] Basic implementation and API -> https://github.com/IgniteUI/igniteui-angular/pull/6848
- [x] Default UI – https://github.com/IgniteUI/igniteui-angular/pull/6984
- [x] TreeGrid - PB
- [x] HierarhicalGrid - SK

Ghost row changes tasks:
-	[x] Flat Grid Ghost rows - #7104
- 	[x] Excel exporter (change according to spec) (all grids) -> МК (https://github.com/IgniteUI/igniteui-angular/pull/7069)
-	[x] GroupBy (flat grid)-> MD
-	[x] Paging (all grids) -> SS
-	[x] `IgxPinnedIndicatorTemplateDirective` implementation - #7104
-	[x] getSelectedData test/fix for all grid types - #6979
-	[x] Default 'Pinned' chip to appear regardless of first column template - #7104
-	[x] Default 'Pinned' label in chip localization - #7104
-	[x] Search integration (all grids) 
-	[x] Add aria-disabled prop for ghost rows -> SK #7104
- 	[x] Ghost row selection on space, shift selection?

Feature Integrations:

-	[x] Updating -> https://github.com/IgniteUI/igniteui-angular/pull/6907
-	[x] Hiding -> https://github.com/IgniteUI/igniteui-angular/pull/6967
-	[x] Filtering -> https://github.com/IgniteUI/igniteui-angular/pull/6884
-	[x] Sorting -> https://github.com/IgniteUI/igniteui-angular/pull/6878
-	[x] Summaries -> #6942
-	[x] Master-Details -> #6909 
-	[x] MRL -> #6924
-	[x] Search -> #6919
- 	[x] State persistence directive -> https://github.com/IgniteUI/igniteui-angular/pull/6968
-  	[x] Navigation - should be resolved by https://github.com/IgniteUI/igniteui-angular/pull/6910

Docs and Samples
-	[x] Update Changelog -> https://github.com/IgniteUI/igniteui-angular/pull/6930
-	[x] Documentation – new topic. - https://github.com/IgniteUI/igniteui-docfx/issues/1791
-	[x] Samples 
    - [x] Potential sample with drag & drop of rows between pin/unpin area. - #1870
    - [x] Sample showing row pinning with remote virtualization and features (pinning cache in the service) -> https://github.com/IgniteUI/igniteui-angular-samples/pull/1883
