### ISSUE TITLE
Allow pinning on the right in igxGrid, igxTreeGrid and igxHierarchicalGrid

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#6676]
Issue for tracking progress:

Parent: #5879 

- [x] Spec update
- [x] Implement and automate skeleton right side pinning
- [x] Update CHANGELOG - SS
- [x] Update igxTreeGrid and igxHierarchicalGrid templates - PB - #6791 
- [x] Resolve Multi-column header scenario - MK -> https://github.com/IgniteUI/igniteui-angular/pull/6782
- [x] Resolve Multi-row-layout scenario - MK
- [x] Resolve Column Moving scenario - VM
- [x] Resolve Summaries scenario - DK -> https://github.com/IgniteUI/igniteui-angular/pull/6787
- [x] Fix KBD Nav -  Currently navigateTo works with right pinning, which means that it should work out of the box once the navigation service refactoring is complete. Related issue is: https://github.com/IgniteUI/igniteui-angular/issues/6747

- [x] Showcase sample - PB -> IgniteUI/igniteui-angular-samples#1825
- [x] Docs update - MK -> https://github.com/IgniteUI/igniteui-docfx/pull/1799
- [x] Row selectors and right pinning -  MK -> https://github.com/IgniteUI/igniteui-angular/pull/6775
- [x] Search and right pinning - MK -> https://github.com/IgniteUI/igniteui-angular/pull/6808
- [x] Extensive manual testing(involve a lot of features)
- [ ] Close #5879
