### ISSUE TITLE
Action Strip component

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular#6941]
Create a new component that can be templated to show a set of actions contextual to the component over which it is shown.

Spec: https://github.com/IgniteUI/igniteui-angular/wiki/Action-Strip-Component

Sub-tasks:
- [x] README for the feature
- [x] Changelog
- [x] Implement base grid action component which should be inherited by all pinning and editing grid action components
- [x] Restrict grid action usage outside of a grid context. Those actions should not appear if they don't have defined grid
- [x] Styling ActionStrip and grid action components - #7117
- [x] have my action strip layout respect display densities i.e. for comfortable 24px till action strip border; for cosy 16px till action strip border; for compact 12px till action strip border. The spacing between the actions is not affected by the display density and is 4px between actions
- [x] Remove `id` and `isMenu` @Inputs
- [x] Implement navigate to disabled row
- [x] Inject Action Strip to grid aciton child and use its context to retrieve the current context and grid, also remove the @Inputs for grid and context

- [x] Topic - https://github.com/igniteui/igniteui-docfx/issues/1841
- [x] Sample - https://github.com/igniteui/igniteui-angular-samples/issues/1872
