### ISSUE TITLE
igxTreeGrid + Row Pinning issues

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#7141]
- [x] Selection is still disabled for ghost rows (to be tested in https://github.com/IgniteUI/igniteui-angular/pull/7104)
- [x] Pinning a root record changes summary result which means the summary pipe probably doesn't work correctly with pinned records
- [x] Export to csv exports pinned records with empty values
- [x] IMO filtered out rows that appear only because they are related to filtered in rows should not show they are pinned (because their pinned counterparts are not there #7172 
- [x] When setting the pinned property of the TreeGridRow an error is thrown: Cannot set property pinned of [object Object] which has only a getter. You can still pin/unpin via the methods. - https://github.com/IgniteUI/igniteui-angular/pull/7194
- [x] TreeGrid does not retain the order in which the rows are pinned but instead applies the original order from the data source to the pinned area. For example if you pin the second row and then first one, the pinned rows should be in order [2, 1], but are instead in order [1, 2]. - #7216 
- [x] Search - Result item count is incorrect if a row that does not have matching results is pinned. Can be reproduced by searching by an unique value that exist in just 1 row and then pinning some other unrelated row. The count is 2, however only 1 match exists. - #7148
- [x] Search - Result item count is incorrect (doubled) and navigation between matches does not work if a row is pinned. - #7148
Can be reproduced by searching by a value that exists once in every row, observe the matches count, then clear search and pin any row and apply same search value and observe that now the match count is doubled. Nothing seems to be marked as active when you use findNext/findPrev.
- [x] filteredSortedData is incorrect - #7148 

![treegrid-search](https://user-images.githubusercontent.com/10397980/79978330-69a4c680-84a8-11ea-91a5-58b3acc322fa.gif)

- [x] Paging - When on last page, pinning a row show empty grid message below the data - https://github.com/IgniteUI/igniteui-angular/pull/7197

![image](https://user-images.githubusercontent.com/10397980/79984759-4b43c880-84b2-11ea-8a8f-14ff4b7dc0d5.png)
